### ISSUE TITLE
Problème pagination

### ISSUE THREAD

**Issue by jonasVallat** [julien331/dont-forget-to-sleep-jee#23]
Quand il y a suffisamment de tâches (>3) pour qu'il y ait une deuxième page, le label de pagination  au-dessus de la liste des tâches n'affiche toujours qu'une seule page et les flèches ne permettent pas d'accéder aux autres pages.
On peut cependant accéder à ces autres pages si on modifie l'URL manuellement.

**Comment by teo-schaffner** [comment]
Flèches ne fonctionnent pas --> normal, pas encore implémentées

**Comment by teo-schaffner** [comment]
Pour le bug des pages, je suis dessus

**Comment by teo-schaffner** [comment]
Fixé nombre de pages dans le commit b20f7ac5c6499680d80b4c2f8c88c8cb586f1857
Pour les flèches, je m'y mets maintenant.

**Comment by teo-schaffner** [comment]
Flèches réglées dans le commit 14c7c069687e701320a40cecb86b2ab905c97f58
